ExternalProject_Add(ceres
  URL http://ceres-solver.org/ceres-solver-1.10.0.tar.gz
  URL_MD5 dbf9f452bd46e052925b835efea9ab16
  BINARY_DIR ${SB_BUILD_DIR}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${SB_DOWNLOAD_LOCATION}
  CMAKE_ARGS
    -DCMAKE_C_FLAGS=-fPIC
    -DCMAKE_CXX_FLAGS=-fPIC
    -DBUILD_EXAMPLES=OFF
    -DBUILD_TESTING=OFF
    -DCMAKE_INSTALL_PREFIX:PATH=${SB_INSTALL_PREFIX}
)

set(CERES_DIR ${SB_INSTALL_PREFIX}/share)