message(STATUS ${CERES_DIR})

ExternalProject_Add(opensfm
  URL https://github.com/edgarriba/OpenSfM/archive/odm-1.zip
  URL_MD5 b517e83489c709eee1d8be76b16976a7
  BINARY_DIR ${SB_BUILD_DIR}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${SB_DOWNLOAD_LOCATION}
  CMAKE_ARGS
    -DCERES_ROOT_DIR=${CERES_DIR}
    -DCMAKE_INSTALL_PREFIX:PATH=${SB_INSTALL_PREFIX}
)

set(OPENSFM_DIR ${SB_INSTALL_PREFIX}/share)